// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"time"

	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ActivityEventType.
const (
	PostArchived    ActivityEventType = "post.archived"
	PostCreated     ActivityEventType = "post.created"
	PostDeleted     ActivityEventType = "post.deleted"
	PostPublished   ActivityEventType = "post.published"
	PostRestored    ActivityEventType = "post.restored"
	PostUnpublished ActivityEventType = "post.unpublished"
	PostUpdated     ActivityEventType = "post.updated"
)

// Valid indicates whether the value is a known member of the ActivityEventType enum.
func (e ActivityEventType) Valid() bool {
	switch e {
	case PostArchived:
		return true
	case PostCreated:
		return true
	case PostDeleted:
		return true
	case PostPublished:
		return true
	case PostRestored:
		return true
	case PostUnpublished:
		return true
	case PostUpdated:
		return true
	default:
		return false
	}
}

// Defines values for AuthTokensTokenType.
const (
	AuthTokensTokenTypeBearer AuthTokensTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the AuthTokensTokenType enum.
func (e AuthTokensTokenType) Valid() bool {
	switch e {
	case AuthTokensTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for BulkRequestAction.
const (
	AddTag    BulkRequestAction = "addTag"
	Archive   BulkRequestAction = "archive"
	Delete    BulkRequestAction = "delete"
	Publish   BulkRequestAction = "publish"
	RemoveTag BulkRequestAction = "removeTag"
	Unpublish BulkRequestAction = "unpublish"
)

// Valid indicates whether the value is a known member of the BulkRequestAction enum.
func (e BulkRequestAction) Valid() bool {
	switch e {
	case AddTag:
		return true
	case Archive:
		return true
	case Delete:
		return true
	case Publish:
		return true
	case RemoveTag:
		return true
	case Unpublish:
		return true
	default:
		return false
	}
}

// Defines values for LoginResultTokenType.
const (
	LoginResultTokenTypeBearer LoginResultTokenType = "Bearer"
)

// Valid indicates whether the value is a known member of the LoginResultTokenType enum.
func (e LoginResultTokenType) Valid() bool {
	switch e {
	case LoginResultTokenTypeBearer:
		return true
	default:
		return false
	}
}

// Defines values for PostStatus.
const (
	Archived  PostStatus = "archived"
	Draft     PostStatus = "draft"
	Published PostStatus = "published"
)

// Valid indicates whether the value is a known member of the PostStatus enum.
func (e PostStatus) Valid() bool {
	switch e {
	case Archived:
		return true
	case Draft:
		return true
	case Published:
		return true
	default:
		return false
	}
}

// Defines values for Sort.
const (
	SortCreatedAt        Sort = "createdAt"
	SortMinusCreatedAt   Sort = "-createdAt"
	SortMinusPublishedAt Sort = "-publishedAt"
	SortMinusTitle       Sort = "-title"
	SortMinusUpdatedAt   Sort = "-updatedAt"
	SortPublishedAt      Sort = "publishedAt"
	SortTitle            Sort = "title"
	SortUpdatedAt        Sort = "updatedAt"
)

// Valid indicates whether the value is a known member of the Sort enum.
func (e Sort) Valid() bool {
	switch e {
	case SortCreatedAt:
		return true
	case SortMinusCreatedAt:
		return true
	case SortMinusPublishedAt:
		return true
	case SortMinusTitle:
		return true
	case SortMinusUpdatedAt:
		return true
	case SortPublishedAt:
		return true
	case SortTitle:
		return true
	case SortUpdatedAt:
		return true
	default:
		return false
	}
}

// Defines values for ListPostsParamsSort.
const (
	ListPostsParamsSortCreatedAt        ListPostsParamsSort = "createdAt"
	ListPostsParamsSortMinusCreatedAt   ListPostsParamsSort = "-createdAt"
	ListPostsParamsSortMinusPublishedAt ListPostsParamsSort = "-publishedAt"
	ListPostsParamsSortMinusTitle       ListPostsParamsSort = "-title"
	ListPostsParamsSortMinusUpdatedAt   ListPostsParamsSort = "-updatedAt"
	ListPostsParamsSortPublishedAt      ListPostsParamsSort = "publishedAt"
	ListPostsParamsSortTitle            ListPostsParamsSort = "title"
	ListPostsParamsSortUpdatedAt        ListPostsParamsSort = "updatedAt"
)

// Valid indicates whether the value is a known member of the ListPostsParamsSort enum.
func (e ListPostsParamsSort) Valid() bool {
	switch e {
	case ListPostsParamsSortCreatedAt:
		return true
	case ListPostsParamsSortMinusCreatedAt:
		return true
	case ListPostsParamsSortMinusPublishedAt:
		return true
	case ListPostsParamsSortMinusTitle:
		return true
	case ListPostsParamsSortMinusUpdatedAt:
		return true
	case ListPostsParamsSortPublishedAt:
		return true
	case ListPostsParamsSortTitle:
		return true
	case ListPostsParamsSortUpdatedAt:
		return true
	default:
		return false
	}
}

// ActivityEvent defines model for ActivityEvent.
type ActivityEvent struct {
	Actor     string    `json:"actor"`
	CreatedAt time.Time `json:"createdAt"`
	Id        string    `json:"id"`
	PostId    *string   `json:"postId,omitempty"`

	// PostTitle Title at the time of the event.
	PostTitle *string           `json:"postTitle,omitempty"`
	Type      ActivityEventType `json:"type"`
}

// ActivityEventType defines model for ActivityEvent.Type.
type ActivityEventType string

// ActivityPage defines model for ActivityPage.
type ActivityPage struct {
	Items      []ActivityEvent `json:"items"`
	NextCursor *string         `json:"nextCursor,omitempty"`
}

// AuthTokens defines model for AuthTokens.
type AuthTokens struct {
	// AccessToken Signed JWT. Send it as `Authorization: Bearer <accessToken>`.
	// Claims: `sub` (user id), `iat`, `exp`, `jti`.
	//
	//
	// Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzEiLCJleHAiOjE3OTEyMDg1MDB9.c2lnbmF0dXJl
	AccessToken string `json:"accessToken"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Example: 900
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Opaque random string, valid for days (the server decides). Single use:
	// every `/auth/refresh` call returns a new one and revokes the old one.
	//
	//
	// Example: 4b7e1c9a0d2f4f1e9a3c6d8b5e7f0a12
	RefreshToken string              `json:"refreshToken"`
	TokenType    AuthTokensTokenType `json:"tokenType"`
}

// AuthTokensTokenType defines model for AuthTokens.TokenType.
type AuthTokensTokenType string

// BulkRequest defines model for BulkRequest.
type BulkRequest struct {
	Action BulkRequestAction `json:"action"`
	Ids    []string          `json:"ids"`

	// Tag Required for `addTag` and `removeTag`.
	Tag *string `json:"tag,omitempty"`
}

// BulkRequestAction defines model for BulkRequest.Action.
type BulkRequestAction string

// BulkResult defines model for BulkResult.
type BulkResult struct {
	Failed []struct {
		Id string `json:"id"`

		// Reason Example: not found
		Reason string `json:"reason"`
	} `json:"failed"`
	Succeeded []string `json:"succeeded"`
}

// Credentials defines model for Credentials.
type Credentials struct {
	Email    openapi_types.Email `json:"email"`
	Password string              `json:"password"`
}

// Health defines model for Health.
type Health struct {
	// Status Example: ok
	Status string `json:"status"`
}

// LoginResult defines model for LoginResult.
type LoginResult struct {
	// AccessToken Signed JWT. Send it as `Authorization: Bearer <accessToken>`.
	// Claims: `sub` (user id), `iat`, `exp`, `jti`.
	//
	//
	// Example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzEiLCJleHAiOjE3OTEyMDg1MDB9.c2lnbmF0dXJl
	AccessToken string `json:"accessToken"`

	// ExpiresIn Seconds until the access token expires.
	//
	// Example: 900
	ExpiresIn int `json:"expiresIn"`

	// RefreshToken Opaque random string, valid for days (the server decides). Single use:
	// every `/auth/refresh` call returns a new one and revokes the old one.
	//
	//
	// Example: 4b7e1c9a0d2f4f1e9a3c6d8b5e7f0a12
	RefreshToken string               `json:"refreshToken"`
	TokenType    LoginResultTokenType `json:"tokenType"`
	User         User                 `json:"user"`
}

// LoginResultTokenType defines model for LoginResult.TokenType.
type LoginResultTokenType string

// Post defines model for Post.
type Post struct {
	// Body Markdown.
	//
	// Example: ## Why a test bed
	//
	// Before any number, a dataset you can trust.
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	Excerpt   *string   `json:"excerpt,omitempty"`

	// Id Example: 01J9ZQ3K8M7V2X4N6P1R5T0WYB
	Id          string     `json:"id"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// Slug Example: a-test-bed-worth-trusting
	Slug   string     `json:"slug"`
	Status PostStatus `json:"status"`

	// Tags Example: ["postgres","performance"]
	Tags []string `json:"tags"`

	// Title Example: A test bed worth trusting
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Example: 7
	Version int `json:"version"`

	// WordCount Example: 1840
	WordCount int `json:"wordCount"`
}

// PostCreate defines model for PostCreate.
type PostCreate struct {
	Body    *string `json:"body,omitempty"`
	Excerpt *string `json:"excerpt,omitempty"`

	// Slug Generated from the title when omitted.
	Slug  *string   `json:"slug,omitempty"`
	Tags  *[]string `json:"tags,omitempty"`
	Title string    `json:"title"`
}

// PostPage defines model for PostPage.
type PostPage struct {
	Items      []PostSummary `json:"items"`
	NextCursor *string       `json:"nextCursor,omitempty"`

	// Total Count of rows matching the filters (not just this page).
	Total *int `json:"total,omitempty"`
}

// PostStatus defines model for PostStatus.
type PostStatus string

// PostSummary defines model for PostSummary.
type PostSummary struct {
	CreatedAt time.Time `json:"createdAt"`
	Excerpt   *string   `json:"excerpt,omitempty"`

	// Id Example: 01J9ZQ3K8M7V2X4N6P1R5T0WYB
	Id          string     `json:"id"`
	PublishedAt *time.Time `json:"publishedAt,omitempty"`

	// Slug Example: a-test-bed-worth-trusting
	Slug   string     `json:"slug"`
	Status PostStatus `json:"status"`

	// Tags Example: ["postgres","performance"]
	Tags []string `json:"tags"`

	// Title Example: A test bed worth trusting
	Title     string    `json:"title"`
	UpdatedAt time.Time `json:"updatedAt"`

	// Version Example: 7
	Version int `json:"version"`

	// WordCount Example: 1840
	WordCount int `json:"wordCount"`
}

// PostUpdate defines model for PostUpdate.
type PostUpdate struct {
	Body    *string     `json:"body,omitempty"`
	Excerpt *string     `json:"excerpt,omitempty"`
	Slug    *string     `json:"slug,omitempty"`
	Status  *PostStatus `json:"status,omitempty"`
	Tags    *[]string   `json:"tags,omitempty"`
	Title   *string     `json:"title,omitempty"`
}

// Problem defines model for Problem.
type Problem struct {
	Detail *string `json:"detail,omitempty"`

	// Errors Field-level problems, for forms.
	Errors *[]struct {
		// Field Example: title
		Field string `json:"field"`

		// Message Example: must not be empty
		Message string `json:"message"`
	} `json:"errors,omitempty"`

	// Extensions Extra data. On 412 this holds `current` (the latest Post).
	Extensions *map[string]interface{} `json:"extensions,omitempty"`

	// Status Example: 422
	Status int `json:"status"`

	// Title Example: Validation failed
	Title string `json:"title"`

	// Type Example: about:blank
	Type string `json:"type"`
}

// RefreshTokenRequest defines model for RefreshTokenRequest.
type RefreshTokenRequest struct {
	RefreshToken string `json:"refreshToken"`
}

// Revision defines model for Revision.
type Revision struct {
	// Author Example: david
	Author    string    `json:"author"`
	Body      string    `json:"body"`
	CreatedAt time.Time `json:"createdAt"`
	Excerpt   *string   `json:"excerpt,omitempty"`
	PostId    string    `json:"postId"`
	Title     string    `json:"title"`
	Version   int       `json:"version"`
}

// RevisionPage defines model for RevisionPage.
type RevisionPage struct {
	Items      []Revision `json:"items"`
	NextCursor *string    `json:"nextCursor,omitempty"`
}

// Stats defines model for Stats.
type Stats struct {
	Counts struct {
		Archived  int `json:"archived"`
		Draft     int `json:"draft"`
		Published int `json:"published"`
	} `json:"counts"`

	// EditsPerDay Last 30 days, oldest first, one entry per day.
	EditsPerDay []struct {
		Date  openapi_types.Date `json:"date"`
		Edits int                `json:"edits"`
	} `json:"editsPerDay"`
	WordsPublished int `json:"wordsPublished"`
}

// TagCount defines model for TagCount.
type TagCount struct {
	// Count Example: 3
	Count int `json:"count"`

	// Name Example: postgres
	Name string `json:"name"`
}

// User defines model for User.
type User struct {
	Email openapi_types.Email `json:"email"`
	Id    string              `json:"id"`
	Name  string              `json:"name"`
}

// ActivityPostId defines model for ActivityPostId.
type ActivityPostId = string

// Cursor defines model for Cursor.
type Cursor = string

// IfMatch Example: "7"
type IfMatch = string

// Limit defines model for Limit.
type Limit = int

// PostId Example: 01J9ZQ3K8M7V2X4N6P1R5T0WYB
type PostId = string

// RevisionVersion defines model for RevisionVersion.
type RevisionVersion = int

// SearchQuery defines model for SearchQuery.
type SearchQuery = string

// Sort defines model for Sort.
type Sort string

// StatusFilter defines model for StatusFilter.
type StatusFilter = []PostStatus

// TagFilter defines model for TagFilter.
type TagFilter = string

// ActivityPageResponse defines model for ActivityPageResponse.
type ActivityPageResponse = ActivityPage

// AuthTokensResponse defines model for AuthTokensResponse.
type AuthTokensResponse = AuthTokens

// BulkResultResponse defines model for BulkResultResponse.
type BulkResultResponse = BulkResult

// ConflictResponse defines model for ConflictResponse.
type ConflictResponse = Problem

// HealthResponse defines model for HealthResponse.
type HealthResponse = Health

// LoginResultResponse defines model for LoginResultResponse.
type LoginResultResponse = LoginResult

// NotFoundResponse defines model for NotFoundResponse.
type NotFoundResponse = Problem

// PostCreatedResponse defines model for PostCreatedResponse.
type PostCreatedResponse = Post

// PostPageResponse defines model for PostPageResponse.
type PostPageResponse = PostPage

// PostResponse defines model for PostResponse.
type PostResponse = Post

// PreconditionFailedResponse defines model for PreconditionFailedResponse.
type PreconditionFailedResponse = Problem

// PreconditionRequiredResponse defines model for PreconditionRequiredResponse.
type PreconditionRequiredResponse = Problem

// RevisionPageResponse defines model for RevisionPageResponse.
type RevisionPageResponse = RevisionPage

// StatsResponse defines model for StatsResponse.
type StatsResponse = Stats

// TagListResponse defines model for TagListResponse.
type TagListResponse = []TagCount

// UnauthorizedResponse defines model for UnauthorizedResponse.
type UnauthorizedResponse = Problem

// UserResponse defines model for UserResponse.
type UserResponse = User

// ValidationErrorResponse defines model for ValidationErrorResponse.
type ValidationErrorResponse = Problem

// LoginRequest defines model for LoginRequest.
type LoginRequest = Credentials

// PostBulkRequest defines model for PostBulkRequest.
type PostBulkRequest = BulkRequest

// PostCreateRequest defines model for PostCreateRequest.
type PostCreateRequest = PostCreate

// PostUpdateRequest defines model for PostUpdateRequest.
type PostUpdateRequest = PostUpdate

// ListActivityParams defines parameters for ListActivity.
type ListActivityParams struct {
	PostId *ActivityPostId `form:"postId,omitempty" json:"postId,omitempty"`
	Limit  *Limit          `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque value from a previous `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListPostsParams defines parameters for ListPosts.
type ListPostsParams struct {
	// Status Repeat to filter by several statuses.
	Status *StatusFilter `form:"status,omitempty" json:"status,omitempty"`
	Tag    *TagFilter    `form:"tag,omitempty" json:"tag,omitempty"`

	// Q Case-insensitive match on title, excerpt and body.
	Q *SearchQuery `form:"q,omitempty" json:"q,omitempty"`

	// Sort Field name, prefixed with `-` for descending.
	Sort  *ListPostsParamsSort `form:"sort,omitempty" json:"sort,omitempty"`
	Limit *Limit               `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque value from a previous `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// ListPostsParamsSort defines parameters for ListPosts.
type ListPostsParamsSort string

// DeletePostParams defines parameters for DeletePost.
type DeletePostParams struct {
	// IfMatch The `ETag` from the last read of this post, e.g. `"7"`.
	IfMatch IfMatch `json:"If-Match"`
}

// UpdatePostParams defines parameters for UpdatePost.
type UpdatePostParams struct {
	// IfMatch The `ETag` from the last read of this post, e.g. `"7"`.
	IfMatch IfMatch `json:"If-Match"`
}

// ListRevisionsParams defines parameters for ListRevisions.
type ListRevisionsParams struct {
	Limit *Limit `form:"limit,omitempty" json:"limit,omitempty"`

	// Cursor Opaque value from a previous `nextCursor`.
	Cursor *Cursor `form:"cursor,omitempty" json:"cursor,omitempty"`
}

// RestoreRevisionParams defines parameters for RestoreRevision.
type RestoreRevisionParams struct {
	// IfMatch The `ETag` from the last read of this post, e.g. `"7"`.
	IfMatch IfMatch `json:"If-Match"`
}

// LoginJSONRequestBody defines body for Login for application/json ContentType.
type LoginJSONRequestBody = Credentials

// LogoutJSONRequestBody defines body for Logout for application/json ContentType.
type LogoutJSONRequestBody = RefreshTokenRequest

// RefreshTokensJSONRequestBody defines body for RefreshTokens for application/json ContentType.
type RefreshTokensJSONRequestBody = RefreshTokenRequest

// CreatePostJSONRequestBody defines body for CreatePost for application/json ContentType.
type CreatePostJSONRequestBody = PostCreate

// BulkPostsJSONRequestBody defines body for BulkPosts for application/json ContentType.
type BulkPostsJSONRequestBody = BulkRequest

// UpdatePostJSONRequestBody defines body for UpdatePost for application/json ContentType.
type UpdatePostJSONRequestBody = PostUpdate
