// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

// ServerUrlLocalBackend defines the Server URL for Local backend
const ServerUrlLocalBackend = "http://localhost:8080/api/v1"

// ServerUrlPrismMockServer defines the Server URL for Prism mock server
const ServerUrlPrismMockServer = "http://localhost:8082"
