/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Liveness check */
        get: operations["getHealth"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Log in with email and password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/refresh": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Swap a refresh token for a new token pair
         * @description Needs no access token. A refresh token works once. If a refresh token that
         *     was already used turns up again, the server treats it as stolen and revokes
         *     every refresh token of that user, so the next call returns 401 and the
         *     client has to log in again.
         */
        post: operations["refreshTokens"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Revoke a refresh token
         * @description Needs no access token, because the access token may already have expired.
         *     Always returns 204, also for an unknown or already revoked token. The
         *     access token itself stays valid until it expires (at most `expiresIn`
         *     seconds); the client should just drop it.
         */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Current user */
        get: operations["getMe"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List posts (without body) */
        get: operations["listPosts"];
        put?: never;
        /** Create a draft post */
        post: operations["createPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Apply one action to many posts
         * @description Not atomic. Each id is handled on its own; the response says which
         *     succeeded and which failed (with a reason). Built for multi-select
         *     in the posts table.
         */
        post: operations["bulkPosts"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /** Get a post with its body */
        get: operations["getPost"];
        put?: never;
        post?: never;
        /** Delete a post */
        delete: operations["deletePost"];
        options?: never;
        head?: never;
        /**
         * Update fields of a post
         * @description Send only the fields that change. Changing `status` to `published`
         *     sets `publishedAt` on first publish. Every successful update that
         *     changes title, excerpt or body adds a revision.
         */
        patch: operations["updatePost"];
        trace?: never;
    };
    "/posts/{id}/revisions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /** Revision history, newest first */
        get: operations["listRevisions"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/revisions/{version}/restore": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
                version: components["parameters"]["RevisionVersion"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Copy an old revision back into the post
         * @description Creates a new revision; history is never rewritten.
         */
        post: operations["restoreRevision"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/posts/{id}/export": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        /**
         * Markdown with front matter
         * @description Same shape the existing blog pipeline reads (`title`, `description`,
         *     `date`, `tags`, `slug`). Lets a post be copied into the Jekyll repo
         *     by hand or by script. Does not publish anywhere.
         */
        get: operations["exportPost"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tags": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** All tags with usage counts */
        get: operations["listTags"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/activity": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Audit trail, newest first */
        get: operations["listActivity"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/stats": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Numbers for the dashboard home */
        get: operations["getStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        ActivityEvent: {
            id: string;
            /** @enum {string} */
            type: "post.created" | "post.updated" | "post.published" | "post.unpublished" | "post.archived" | "post.deleted" | "post.restored";
            postId?: string | null;
            /** @description Title at the time of the event. */
            postTitle?: string;
            actor: string;
            /** Format: date-time */
            createdAt: string;
        };
        ActivityPage: {
            items: components["schemas"]["ActivityEvent"][];
            nextCursor?: string | null;
        };
        AuthTokens: {
            /**
             * @description Signed JWT. Send it as `Authorization: Bearer <accessToken>`.
             *     Claims: `sub` (user id), `iat`, `exp`, `jti`.
             * @example eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJ1c2VyXzEiLCJleHAiOjE3OTEyMDg1MDB9.c2lnbmF0dXJl
             */
            accessToken: string;
            /**
             * @description Opaque random string, valid for days (the server decides). Single use:
             *     every `/auth/refresh` call returns a new one and revokes the old one.
             * @example 4b7e1c9a0d2f4f1e9a3c6d8b5e7f0a12
             */
            refreshToken: string;
            /** @enum {string} */
            tokenType: "Bearer";
            /**
             * @description Seconds until the access token expires.
             * @example 900
             */
            expiresIn: number;
        };
        BulkRequest: {
            ids: string[];
            /** @enum {string} */
            action: "publish" | "unpublish" | "archive" | "delete" | "addTag" | "removeTag";
            /** @description Required for `addTag` and `removeTag`. */
            tag?: string;
        };
        BulkResult: {
            succeeded: string[];
            failed: {
                id: string;
                /** @example not found */
                reason: string;
            }[];
        };
        Credentials: {
            /** Format: email */
            email: string;
            /** Format: password */
            password: string;
        };
        Health: {
            /** @example ok */
            status: string;
        };
        LoginResult: components["schemas"]["AuthTokens"] & {
            user: components["schemas"]["User"];
        };
        Post: components["schemas"]["PostSummary"] & {
            /**
             * @description Markdown.
             * @example ## Why a test bed
             *
             *     Before any number, a dataset you can trust.
             */
            body: string;
        };
        PostCreate: {
            title: string;
            /** @description Generated from the title when omitted. */
            slug?: string;
            excerpt?: string;
            /** @default  */
            body: string;
            tags?: string[];
        };
        PostPage: {
            items: components["schemas"]["PostSummary"][];
            nextCursor?: string | null;
            /** @description Count of rows matching the filters (not just this page). */
            total?: number;
        };
        /** @enum {string} */
        PostStatus: "draft" | "published" | "archived";
        PostSummary: {
            /** @example 01J9ZQ3K8M7V2X4N6P1R5T0WYB */
            id: string;
            /** @example A test bed worth trusting */
            title: string;
            /** @example a-test-bed-worth-trusting */
            slug: string;
            excerpt?: string;
            status: components["schemas"]["PostStatus"];
            /**
             * @example [
             *       "postgres",
             *       "performance"
             *     ]
             */
            tags: string[];
            /** @example 7 */
            version: number;
            /** @example 1840 */
            wordCount: number;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            updatedAt: string;
            /** Format: date-time */
            publishedAt?: string | null;
        };
        PostUpdate: {
            title?: string;
            slug?: string;
            excerpt?: string;
            body?: string;
            status?: components["schemas"]["PostStatus"];
            tags?: string[];
        };
        Problem: {
            /** @example about:blank */
            type: string;
            /** @example Validation failed */
            title: string;
            /** @example 422 */
            status: number;
            detail?: string;
            /** @description Field-level problems, for forms. */
            errors?: {
                /** @example title */
                field: string;
                /** @example must not be empty */
                message: string;
            }[];
            /** @description Extra data. On 412 this holds `current` (the latest Post). */
            extensions?: {
                [key: string]: unknown;
            };
        };
        RefreshTokenRequest: {
            refreshToken: string;
        };
        Revision: {
            postId: string;
            version: number;
            title: string;
            excerpt?: string;
            body: string;
            /** @example david */
            author: string;
            /** Format: date-time */
            createdAt: string;
        };
        RevisionPage: {
            items: components["schemas"]["Revision"][];
            nextCursor?: string | null;
        };
        Stats: {
            counts: {
                draft: number;
                published: number;
                archived: number;
            };
            wordsPublished: number;
            /** @description Last 30 days, oldest first, one entry per day. */
            editsPerDay: {
                /** Format: date */
                date: string;
                edits: number;
            }[];
        };
        TagCount: {
            /** @example postgres */
            name: string;
            /** @example 3 */
            count: number;
        };
        User: {
            id: string;
            /** Format: email */
            email: string;
            name: string;
        };
    };
    responses: {
        /** @description A page of activity events */
        ActivityPageResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["ActivityPage"];
            };
        };
        /** @description A new token pair. The refresh token you sent is now revoked. */
        AuthTokensResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["AuthTokens"];
            };
        };
        /** @description Per-id outcome */
        BulkResultResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["BulkResult"];
            };
        };
        /** @description Conflicts with existing data, for example the slug is already in use */
        ConflictResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Service is up */
        HealthResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Health"];
            };
        };
        /** @description Logged in. Tokens and the user. */
        LoginResultResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["LoginResult"];
            };
        };
        /** @description Markdown file with front matter */
        MarkdownResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "text/markdown": string;
            };
        };
        /** @description Done, nothing to return */
        NoContentResponse: {
            headers: {
                [name: string]: unknown;
            };
            content?: never;
        };
        /** @description No such resource */
        NotFoundResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The created post */
        PostCreatedResponse: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Post"];
            };
        };
        /** @description A page of posts */
        PostPageResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["PostPage"];
            };
        };
        /** @description The post */
        PostResponse: {
            headers: {
                ETag: components["headers"]["ETag"];
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Post"];
            };
        };
        /** @description Stale `If-Match`. `extensions.current` holds the latest post. */
        PreconditionFailedResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description `If-Match` header missing */
        PreconditionRequiredResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description A page of revisions */
        RevisionPageResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["RevisionPage"];
            };
        };
        /** @description Counts and a 30-day edit series */
        StatsResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Stats"];
            };
        };
        /** @description Tags, most used first */
        TagListResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["TagCount"][];
            };
        };
        /** @description Missing, invalid or expired token (access token, refresh token, or wrong login) */
        UnauthorizedResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description The user */
        UserResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["User"];
            };
        };
        /** @description Validation failed. `errors` lists the fields. */
        ValidationErrorResponse: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        ActivityPostId: string;
        /** @description Opaque value from a previous `nextCursor`. */
        Cursor: string;
        /** @description The `ETag` from the last read of this post, e.g. `"7"`. */
        IfMatch: string;
        Limit: number;
        PostId: string;
        RevisionVersion: number;
        /** @description Case-insensitive match on title, excerpt and body. */
        SearchQuery: string;
        /** @description Field name, prefixed with `-` for descending. */
        Sort: "updatedAt" | "-updatedAt" | "createdAt" | "-createdAt" | "publishedAt" | "-publishedAt" | "title" | "-title";
        /** @description Repeat to filter by several statuses. */
        StatusFilter: components["schemas"]["PostStatus"][];
        TagFilter: string;
    };
    requestBodies: {
        LoginRequest: {
            content: {
                "application/json": components["schemas"]["Credentials"];
            };
        };
        PostBulkRequest: {
            content: {
                "application/json": components["schemas"]["BulkRequest"];
            };
        };
        PostCreateRequest: {
            content: {
                "application/json": components["schemas"]["PostCreate"];
            };
        };
        PostUpdateRequest: {
            content: {
                "application/json": components["schemas"]["PostUpdate"];
            };
        };
        RefreshTokenRequest: {
            content: {
                "application/json": components["schemas"]["RefreshTokenRequest"];
            };
        };
    };
    headers: {
        /** @description Current post version in quotes, e.g. `"7"`. */
        ETag: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getHealth: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["HealthResponse"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["LoginRequest"];
        responses: {
            200: components["responses"]["LoginResultResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            422: components["responses"]["ValidationErrorResponse"];
        };
    };
    refreshTokens: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RefreshTokenRequest"];
        responses: {
            200: components["responses"]["AuthTokensResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            422: components["responses"]["ValidationErrorResponse"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["RefreshTokenRequest"];
        responses: {
            204: components["responses"]["NoContentResponse"];
            422: components["responses"]["ValidationErrorResponse"];
        };
    };
    getMe: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["UserResponse"];
            401: components["responses"]["UnauthorizedResponse"];
        };
    };
    listPosts: {
        parameters: {
            query?: {
                /** @description Repeat to filter by several statuses. */
                status?: components["parameters"]["StatusFilter"];
                tag?: components["parameters"]["TagFilter"];
                /** @description Case-insensitive match on title, excerpt and body. */
                q?: components["parameters"]["SearchQuery"];
                /** @description Field name, prefixed with `-` for descending. */
                sort?: components["parameters"]["Sort"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque value from a previous `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PostPageResponse"];
            401: components["responses"]["UnauthorizedResponse"];
        };
    };
    createPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PostCreateRequest"];
        responses: {
            201: components["responses"]["PostCreatedResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            409: components["responses"]["ConflictResponse"];
            422: components["responses"]["ValidationErrorResponse"];
        };
    };
    bulkPosts: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PostBulkRequest"];
        responses: {
            200: components["responses"]["BulkResultResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            422: components["responses"]["ValidationErrorResponse"];
        };
    };
    getPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PostResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            404: components["responses"]["NotFoundResponse"];
        };
    };
    deletePost: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from the last read of this post, e.g. `"7"`. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            204: components["responses"]["NoContentResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            404: components["responses"]["NotFoundResponse"];
            412: components["responses"]["PreconditionFailedResponse"];
        };
    };
    updatePost: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from the last read of this post, e.g. `"7"`. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody: components["requestBodies"]["PostUpdateRequest"];
        responses: {
            200: components["responses"]["PostResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            404: components["responses"]["NotFoundResponse"];
            409: components["responses"]["ConflictResponse"];
            412: components["responses"]["PreconditionFailedResponse"];
            422: components["responses"]["ValidationErrorResponse"];
            428: components["responses"]["PreconditionRequiredResponse"];
        };
    };
    listRevisions: {
        parameters: {
            query?: {
                limit?: components["parameters"]["Limit"];
                /** @description Opaque value from a previous `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["RevisionPageResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            404: components["responses"]["NotFoundResponse"];
        };
    };
    restoreRevision: {
        parameters: {
            query?: never;
            header: {
                /** @description The `ETag` from the last read of this post, e.g. `"7"`. */
                "If-Match": components["parameters"]["IfMatch"];
            };
            path: {
                id: components["parameters"]["PostId"];
                version: components["parameters"]["RevisionVersion"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["PostResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            404: components["responses"]["NotFoundResponse"];
            412: components["responses"]["PreconditionFailedResponse"];
        };
    };
    exportPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                id: components["parameters"]["PostId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["MarkdownResponse"];
            401: components["responses"]["UnauthorizedResponse"];
            404: components["responses"]["NotFoundResponse"];
        };
    };
    listTags: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["TagListResponse"];
            401: components["responses"]["UnauthorizedResponse"];
        };
    };
    listActivity: {
        parameters: {
            query?: {
                postId?: components["parameters"]["ActivityPostId"];
                limit?: components["parameters"]["Limit"];
                /** @description Opaque value from a previous `nextCursor`. */
                cursor?: components["parameters"]["Cursor"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["ActivityPageResponse"];
            401: components["responses"]["UnauthorizedResponse"];
        };
    };
    getStats: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            200: components["responses"]["StatsResponse"];
            401: components["responses"]["UnauthorizedResponse"];
        };
    };
}
